[package]
name = "cpu-ze"
version = "0.3.12"
description = "Mini Task Manager — CPU & RAM"
authors = ["CPU-ZE"]
edition = "2021"

[lib]
name = "cpu_ze_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sysinfo = "0.38.4"
tauri-plugin-autostart = "2.5.1"
nvml-wrapper = "0.12.1"
tauri-plugin-updater = "2.10.1"
tauri-plugin-process = "2.3.1"
ureq = { version = "3.3.0", default-features = false, features = ["json"] }
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_System_Memory",
    "Win32_Security",
    "Win32_System_SystemInformation",
    "Win32_System_ProcessStatus",
    "Win32_System_Threading",
    "Win32_System_Performance",
    "Win32_System_IO",
    "Win32_System_LibraryLoader",
    "Win32_System_Registry",
    "Win32_Storage_FileSystem",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
] }

